// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnitlyizrjryrgleesml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuaXRseWl6cmpyeXJnbGVlc21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTUyNjksImV4cCI6MjA2NTk5MTI2OX0.wVe6zcUm1B9EeOQY_2m0pzXe2fj7tTq9oeuJ706GqsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);